export const SET_CURRENT_USER 	= 'SET_CURRENT_USER';

export const SELECT_DEVICE 			= 'SELECT_DEVICE';
export const DELETE_DEVICE 			= 'DELETE_DEVICE';
export const ADD_DEVICE 			= 'ADD_DEVICE';
export const RECEIVE_DEVICES 		= 'RECEIVE_DEVICES';
export const DEVICE_ERROR_OCCURED 	= 'DEVICE_ERROR_OCCURED';
export const RECEIVE_VENDORS		= 'RECEIVE_VENDORS';
export const RECEIVE_PRODUCTS 		= 'RECEIVE_PRODUCTS';

export const SELECT_SCENARIO 	= 'SELECT_SCENARIO';

export const REQUEST_SCENARIOS 	= 'REQUEST_SCENARIOS';
export const DELETE_SCENARIO 	= 'DELETE_SCENARIO';
export const ADD_SCENARIO 		= 'ADD_SCENARIO';
export const RECEIVE_SCENARIOS 	= 'RECEIVE_SCENARIOS';
export const SCENARIO_ERROR_OCCURED = 'SCENARIO_ERROR_OCCURED';

export const SELECT_PRODUCT 	= 'SELECT_PRODUCT';
export const DELETE_PRODUCT 	= 'DELETE_PRODUCT';
export const ADD_PRODUCT 		= 'ADD_PRODUCT';
export const REQUEST_PRODUCTS 	= 'REQUEST_PRODUCTS';

export const REMOVE_BANNER	= 'REMOVE_BANNER';
export const SET_BANNER	= 'SET_BANNER';
