export const SET_CURRENT_USER       = "SET_CURRENT_USER";
export const SET_LOGIN_REQUEST_SENT = "SET_LOGIN_REQUEST_SENT";
export const SET_LOGIN_REQUEST_DONE = "SET_LOGIN_REQUEST_DONE";
export const SIGNUP_USER = "SIGNUP_USER";
export const USER_CREATED = "USER_CREATED";
export const USER_CREATION_FAILED = "USER_CREATION_FAILED";
export const USER_CREATION_REQUEST = "USER_CREATION_REQUEST";

export const FETCH_DEVICES          = "FETCH_DEVICES";
export const RECEIVE_DEVICES        = "RECEIVE_DEVICES";
export const ADD_DEVICE             = "ADD_DEVICE";
export const SELECT_DEVICE          = "SELECT_DEVICE";
export const DELETE_DEVICE          = "DELETE_DEVICE";
export const DEVICE_ERROR_OCCURED   = "DEVICE_ERROR_OCCURED";



export const RECEIVE_VENDORS        = "RECEIVE_VENDORS";
export const FETCH_VENDORS          = "FETCH_VENDORS";
export const FETCH_PRODUCTS         = "FETCH_PRODUCTS";
export const RECEIVE_PRODUCTS       = "RECEIVE_PRODUCTS";
export const PRODUCT_ERROR_OCCURED  = "PRODUCT_ERROR_OCCURED";

export const FETCH_SCENARIOS = "FETCH_SCENARIOS";
export const SELECT_SCENARIO        = "SELECT_SCENARIO";
export const REQUEST_SCENARIOS      = "REQUEST_SCENARIOS";
export const DELETE_SCENARIO        = "DELETE_SCENARIO";
export const ADD_SCENARIO           = "ADD_SCENARIO";
export const RECEIVE_SCENARIOS      = "RECEIVE_SCENARIOS";
export const SCENARIO_ERROR_OCCURED = "SCENARIO_ERROR_OCCURED";

export const SELECT_PRODUCT         = "SELECT_PRODUCT";
export const DELETE_PRODUCT 		= "DELETE_PRODUCT";
export const ADD_PRODUCT 			= "ADD_PRODUCT";
export const REQUEST_PRODUCTS 		= "REQUEST_PRODUCTS";

export const ADD_PRODUCT_REQUEST    = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_ERROR     = "ADD_PRODUCT_ERROR";

export const SET_MESSAGE 			= "SET_MESSAGE";
